/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AppVaultConfigInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LP_VAULT"
      | "PORTFOLIO_VAULT"
      | "TRADE_VAULT"
      | "getLpVault"
      | "getPortfolioVault"
      | "getTradeVault"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "LP_VAULT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PORTFOLIO_VAULT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TRADE_VAULT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLpVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPortfolioVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeVault",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "LP_VAULT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PORTFOLIO_VAULT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TRADE_VAULT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLpVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPortfolioVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeVault",
    data: BytesLike
  ): Result;
}

export interface AppVaultConfig extends BaseContract {
  connect(runner?: ContractRunner | null): AppVaultConfig;
  waitForDeployment(): Promise<this>;

  interface: AppVaultConfigInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LP_VAULT: TypedContractMethod<[], [string], "view">;

  PORTFOLIO_VAULT: TypedContractMethod<[], [string], "view">;

  TRADE_VAULT: TypedContractMethod<[], [string], "view">;

  getLpVault: TypedContractMethod<[], [string], "view">;

  getPortfolioVault: TypedContractMethod<[], [string], "view">;

  getTradeVault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LP_VAULT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PORTFOLIO_VAULT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TRADE_VAULT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLpVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPortfolioVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTradeVault"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
