/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ChainUtils,
  ChainUtilsInterface,
} from "../../../contracts/utils/ChainUtils";

const _abi = [
  {
    inputs: [],
    name: "ARBITRUM_CHAIN_ID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ARBITRUM_SEPOLIA_CHAIN_ID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "arbSys",
    outputs: [
      {
        internalType: "contract ArbSys",
        name: "",
        type: "ArbSys",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6101b061003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100715760003560e01c80631fab59fb1161005a5780631fab59fb146100b8578063cdcdd548146100c2578063e12ed13c146100cb57600080fd5b80631057d40f146100765780631e2ff94f146100a8575b600080fd5b61007e606481565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b425b60405190815260200161009f565b6100aa62066eee81565b6100aa61a4b181565b6100aa600061a4b14614806100e2575062066eee46145b1561015c57606473ffffffffffffffffffffffffffffffffffffffff1663a3b1b31d6040518163ffffffff1660e01b8152600401602060405180830381865afa158015610133573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101579190610161565b905090565b504390565b60006020828403121561017357600080fd5b505191905056fea2646970667358221220dc6f51ccdb31e44157e3f3a9b5468a511d5f20ec7f452cc7c9ad44d160611e9164736f6c63430008120033";

type ChainUtilsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ChainUtilsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ChainUtils__factory extends ContractFactory {
  constructor(...args: ChainUtilsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ChainUtils & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ChainUtils__factory {
    return super.connect(runner) as ChainUtils__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ChainUtilsInterface {
    return new Interface(_abi) as ChainUtilsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ChainUtils {
    return new Contract(address, _abi, runner) as unknown as ChainUtils;
  }
}
