/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRebalance,
  IRebalanceInterface,
} from "../../../contracts/interfaces/IRebalance";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "address",
            name: "targetToken",
            type: "address",
          },
          {
            internalType: "int256",
            name: "minPrice",
            type: "int256",
          },
          {
            internalType: "int256",
            name: "maxPrice",
            type: "int256",
          },
        ],
        internalType: "struct OracleProcess.OracleParam[]",
        name: "oracles",
        type: "tuple[]",
      },
    ],
    name: "autoRebalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRebalance__factory {
  static readonly abi = _abi;
  static createInterface(): IRebalanceInterface {
    return new Interface(_abi) as IRebalanceInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRebalance {
    return new Contract(address, _abi, runner) as unknown as IRebalance;
  }
}
