/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ChainUtilsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ARBITRUM_CHAIN_ID"
      | "ARBITRUM_SEPOLIA_CHAIN_ID"
      | "arbSys"
      | "currentBlock"
      | "currentTimestamp"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ARBITRUM_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITRUM_SEPOLIA_CHAIN_ID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "arbSys", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTimestamp",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ARBITRUM_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITRUM_SEPOLIA_CHAIN_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "arbSys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTimestamp",
    data: BytesLike
  ): Result;
}

export interface ChainUtils extends BaseContract {
  connect(runner?: ContractRunner | null): ChainUtils;
  waitForDeployment(): Promise<this>;

  interface: ChainUtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ARBITRUM_CHAIN_ID: TypedContractMethod<[], [bigint], "view">;

  ARBITRUM_SEPOLIA_CHAIN_ID: TypedContractMethod<[], [bigint], "view">;

  arbSys: TypedContractMethod<[], [string], "view">;

  currentBlock: TypedContractMethod<[], [bigint], "view">;

  currentTimestamp: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ARBITRUM_CHAIN_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ARBITRUM_SEPOLIA_CHAIN_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "arbSys"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
