/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface LiquidationProcessInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "LiquidationAccountIgnored"
      | "LiquidationPositionIgnored"
  ): EventFragment;
}

export namespace LiquidationAccountIgnoredEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationPositionIgnoredEvent {
  export type InputTuple = [positionKey: BytesLike];
  export type OutputTuple = [positionKey: string];
  export interface OutputObject {
    positionKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidationProcess extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidationProcess;
  waitForDeployment(): Promise<this>;

  interface: LiquidationProcessInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "LiquidationAccountIgnored"
  ): TypedContractEvent<
    LiquidationAccountIgnoredEvent.InputTuple,
    LiquidationAccountIgnoredEvent.OutputTuple,
    LiquidationAccountIgnoredEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationPositionIgnored"
  ): TypedContractEvent<
    LiquidationPositionIgnoredEvent.InputTuple,
    LiquidationPositionIgnoredEvent.OutputTuple,
    LiquidationPositionIgnoredEvent.OutputObject
  >;

  filters: {
    "LiquidationAccountIgnored(address)": TypedContractEvent<
      LiquidationAccountIgnoredEvent.InputTuple,
      LiquidationAccountIgnoredEvent.OutputTuple,
      LiquidationAccountIgnoredEvent.OutputObject
    >;
    LiquidationAccountIgnored: TypedContractEvent<
      LiquidationAccountIgnoredEvent.InputTuple,
      LiquidationAccountIgnoredEvent.OutputTuple,
      LiquidationAccountIgnoredEvent.OutputObject
    >;

    "LiquidationPositionIgnored(bytes32)": TypedContractEvent<
      LiquidationPositionIgnoredEvent.InputTuple,
      LiquidationPositionIgnoredEvent.OutputTuple,
      LiquidationPositionIgnoredEvent.OutputObject
    >;
    LiquidationPositionIgnored: TypedContractEvent<
      LiquidationPositionIgnoredEvent.InputTuple,
      LiquidationPositionIgnoredEvent.OutputTuple,
      LiquidationPositionIgnoredEvent.OutputObject
    >;
  };
}
