/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ReferralFacet,
  ReferralFacetInterface,
} from "../../../contracts/facets/ReferralFacet";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getAccountReferral",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "code",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "referralCode",
            type: "bytes32",
          },
        ],
        internalType: "struct Referral.Props",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "code",
        type: "bytes32",
      },
    ],
    name: "isCodeExists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610304806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80636ecc79e41461003b578063e8af7f0814610063575b600080fd5b61004e61004936600461023d565b6100ae565b60405190151581526020015b60405180910390f35b610076610071366004610256565b610144565b60408051825173ffffffffffffffffffffffffffffffffffffffff16815260208084015190820152918101519082015260600161005a565b6040517f6ecc79e40000000000000000000000000000000000000000000000000000000081526004810182905260009073__$0b4aa79a3801f36ddbb6bdfbedce5b4c6d$__90636ecc79e490602401602060405180830381865af415801561011a573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061013e9190610293565b92915050565b604080516060810182526000808252602082018190528183015290517f2f40e73400000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff8316600482015273__$0b4aa79a3801f36ddbb6bdfbedce5b4c6d$__90632f40e73490602401602060405180830381865af41580156101db573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101ff91906102b5565b60408051606081018252825473ffffffffffffffffffffffffffffffffffffffff168152600183015460208201526002909201549082015292915050565b60006020828403121561024f57600080fd5b5035919050565b60006020828403121561026857600080fd5b813573ffffffffffffffffffffffffffffffffffffffff8116811461028c57600080fd5b9392505050565b6000602082840312156102a557600080fd5b8151801515811461028c57600080fd5b6000602082840312156102c757600080fd5b505191905056fea264697066735822122043023723c9e9feebbb4771f8230d41016eb8421a5a6990b12d04e2029ab579f364736f6c63430008120033";

type ReferralFacetConstructorParams =
  | [linkLibraryAddresses: ReferralFacetLibraryAddresses, signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReferralFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === "string" ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    "_isInterface" in xs[0]
  );
};

export class ReferralFacet__factory extends ContractFactory {
  constructor(...args: ReferralFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      const [linkLibraryAddresses, signer] = args;
      super(
        _abi,
        ReferralFacet__factory.linkBytecode(linkLibraryAddresses),
        signer
      );
    }
  }

  static linkBytecode(
    linkLibraryAddresses: ReferralFacetLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode;

    linkedBytecode = linkedBytecode.replace(
      new RegExp("__\\$0b4aa79a3801f36ddbb6bdfbedce5b4c6d\\$__", "g"),
      linkLibraryAddresses["contracts/storage/Referral.sol:Referral"]
        .replace(/^0x/, "")
        .toLowerCase()
    );

    return linkedBytecode;
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReferralFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReferralFacet__factory {
    return super.connect(runner) as ReferralFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReferralFacetInterface {
    return new Interface(_abi) as ReferralFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReferralFacet {
    return new Contract(address, _abi, runner) as unknown as ReferralFacet;
  }
}

export interface ReferralFacetLibraryAddresses {
  ["contracts/storage/Referral.sol:Referral"]: string;
}
